### PR TITLE
fix: add page title to ad page, resolves #17

### LINKED ISSUE #17: 🐛 Bug: /ad page should have a <title>
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

All pages should have a unique title. https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html

### Actual

https://phillyjs.com/ad?month=april&year=2023 doesn't! Let's add one in based on the provided month & year.

### Additional Info

https://github.com/philly-js-club/philly-js-club-website/blob/09740eb5304452a5b6178dcce50cd0a3eeaa50ce/app/routes/ad.tsx is the page's source.

### PR DESCRIPTION
**Pull request by RNR1**
## PR Checklist

- [x] Addresses an existing open issue: fixes #17 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/philly-js-club/philly-js-club-website-remix/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

I added a valid HTML page title to the "Ad" page. 
When the "month" or "year" search params are missing or invalid, the page title will be "Ad | Philly JS Club," otherwise, it will display "Ad (${month} ${year}), same as it will display in the UI.

### CODE REVIEW

File: app/routes/ad.tsx [hunk 1]
```diff
@@ -17,6 +18,18 @@ const monthNames = new Set([
 	"december",
 ]);
 
+export const meta: V2_MetaFunction = ({ location }) => {
+	const params = new URLSearchParams(location.search);
+	const month = params.get("month")?.toLowerCase() ?? "idk";
+	const year = params.get("year")?.toLowerCase() ?? "when";
```
Comment (JoshuaKGoldberg) [inline app/routes/ad.tsx]: [Refactor] We're now duplicating the `params.get ... ` logic. That makes me worry about the two pieces of logic getting out of sync (and is a bit more code to read). How about maing a shared `getMonthAndYear` function or something like that?

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks! Works great ✨ 

Left a suggestion for a refactor - but this could be a nice `good first issue` followup, no worries if you're not interested.

Unless directed otherwise I'll leave this open for a couple days, then merge as-is.

File: app/routes/ad.tsx (hunk 1 above)
Comment (RNR1) [reply app/routes/ad.tsx]: I extracted some utils as suggested, let me know what you think

**Review by JoshuaKGoldberg — APPROVED** [review]
Nerdy guy fist pumping once and going 'sweet'

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @RNR1 for code
